Fix unused parameter warning
Summary:
In D16673230, a pair of new functions were added. One of them was meant to avoid accepting a particular type of channel, but the actual `channel` parameter was not used in the function. This causes the `unused-parameter` error:

```
openr/common/OpenrClient.h:29:62: error: unused parameter 'channel' [-Werror=unused-parameter]
 setCompressionTransform(apache::thrift::RocketClientChannel* channel) {
                                                              ^
```

Reviewed By: saifhhasan

Differential Revision: D16688348

fbshipit-source-id: b8bccf3d49c33dd93e6b9a0aee7c4121920ff271